
-- Add start_date to employees
ALTER TABLE employees ADD COLUMN IF NOT EXISTS start_date DATE;

-- Create hr_tasks table
CREATE TABLE IF NOT EXISTS hr_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id UUID REFERENCES employees(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  category TEXT NOT NULL, -- 'IT', 'HR', 'Logistics', 'Finance'
  status TEXT NOT NULL DEFAULT 'pending', -- 'pending', 'completed'
  priority TEXT NOT NULL DEFAULT 'medium', -- 'high', 'medium', 'low'
  due_date DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE hr_tasks ENABLE ROW LEVEL SECURITY;

-- Policies for hr_tasks
-- HR can view/manage tasks for their own employees
CREATE POLICY "HR can manage tasks for their employees" ON hr_tasks
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM employees
      WHERE employees.id = hr_tasks.employee_id
      AND employees.hr_id = auth.uid()
    )
  );
