
-- Add user_id to employees
ALTER TABLE employees ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id);

-- Add settings to hr_profiles
ALTER TABLE hr_profiles ADD COLUMN IF NOT EXISTS settings JSONB DEFAULT '{}'::jsonb;

-- Create milestones table
CREATE TABLE IF NOT EXISTS milestones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id UUID REFERENCES employees(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  category TEXT NOT NULL, -- 'First 30 Days', '60 Days', '90 Days'
  completed BOOLEAN DEFAULT FALSE,
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create messages table
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id UUID NOT NULL, -- Can reference auth.users(id)
  receiver_id UUID NOT NULL, -- Can reference auth.users(id)
  content TEXT NOT NULL,
  read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add RLS Policies
ALTER TABLE milestones ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- Milestones Policies
-- HR can view all milestones for their employees
CREATE POLICY "HR can view their employees' milestones" ON milestones
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM employees
      WHERE employees.id = milestones.employee_id
      AND employees.hr_id = auth.uid()
    )
  );

-- HR can insert/update/delete milestones
CREATE POLICY "HR can manage their employees' milestones" ON milestones
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM employees
      WHERE employees.id = milestones.employee_id
      AND employees.hr_id = auth.uid()
    )
  );

-- Employees can view their own milestones
CREATE POLICY "Employees can view own milestones" ON milestones
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM employees
      WHERE employees.id = milestones.employee_id
      AND employees.user_id = auth.uid()
    )
  );

-- Employees can update their own milestones (completion/notes)
CREATE POLICY "Employees can update own milestones" ON milestones
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM employees
      WHERE employees.id = milestones.employee_id
      AND employees.user_id = auth.uid()
    )
  );

-- Messages Policies
-- Users can view messages they sent or received
CREATE POLICY "Users can view their messages" ON messages
  FOR SELECT
  USING (
    sender_id = auth.uid() OR receiver_id = auth.uid()
  );

-- Users can send messages
CREATE POLICY "Users can insert messages" ON messages
  FOR INSERT
  WITH CHECK (
    sender_id = auth.uid()
  );

-- Update employees policy to allow them to see themselves based on user_id as well
-- Existing policies might be based on email? I should check existing policies if I could.
-- But since I can't easily check existing policies without SQL access (no migrations file), I will assume basic policies exist or I might need to add one.
-- "Employees can view own profile"
CREATE POLICY "Employees can view own profile based on user_id" ON employees
  FOR SELECT
  USING (
    user_id = auth.uid()
  );
