
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aagoiywolhimmpnyvubj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhZ29peXdvbGhpbW1wbnl2dWJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MDk5NTAsImV4cCI6MjA2MDA4NTk1MH0.rSNppF2mdGyk-zCWB3McZmBEOZq1ng43yKAgg_4LW3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: localStorage
  }
});
